添加模块：显示长时增益效果的具体结束时间
Dalamud-DailyRoutines/DailyRoutines.ModulesPublic pull request #10
Opened 2024-12-26 17:53 UTC by DueDine

## 效果
![image](https://github.com/user-attachments/assets/6ce862e2-2321-4fcf-ad0c-e6858d9d99f8)

2024-12-27 02:52 UTC, AtmoOmen requested changes

2024-12-27 02:52 UTC, AtmoOmen commented on UIOptimization/ShowStatusRemainingTime.cs
> +        if (DService.ClientState.LocalPlayer == null) return string.Empty;
使用 Is 判断

2024-12-27 02:52 UTC, AtmoOmen commented on UIOptimization/ShowStatusRemainingTime.cs
> +        var statusManager = ((Character*)DService.ClientState.LocalPlayer.Address)->GetStatusManager();
需要判断 statusManager 是否为空

2024-12-27 02:52 UTC, AtmoOmen commented on UIOptimization/ShowStatusRemainingTime.cs
> +        if (!statusManager->HasStatus(type)) return string.Empty;
用 GetStatusIndex , 根据是否为 -1 来判断是否存在, 不要用 HasStatus 和 GetStatusIndex 遍历两次

2024-12-27 02:52 UTC, AtmoOmen commented on UIOptimization/ShowStatusRemainingTime.cs
> +        for (var i = 2; i <= 21; i++)
以下的所有 Node 和 Component 全都需要判断是否为空

2024-12-27 13:53 UTC, AtmoOmen commented on UIOptimization/ShowStatusRemainingTime.cs
> +        var addon = DService.Gui.GetAddonByName(args.AddonName);
为什么要再获取一次, 直接 `(AtkUnitBase*)args.Addon` 不就行了吗

2024-12-27 13:54 UTC, AtmoOmen commented on UIOptimization/ShowStatusRemainingTime.cs
> +    private static readonly Dictionary<uint, uint> iconStatusPair = new()
我个人不建议用 Icom 来对应 Status , 因为 Icon 是有复用的,
还是找其他结构好一些

2024-12-27 14:27 UTC, DueDine commented on UIOptimization/ShowStatusRemainingTime.cs
> +    private static readonly Dictionary<uint, uint> iconStatusPair = new()
我也想找别的结构。但不知道 SE 怎么设计的，状态和图标之间没有联系。
![image](https://github.com/user-attachments/assets/e7523dda-43f6-4954-955f-f13779908a19)
状态过期后只是单纯把 OwnerNode 给不可见，内容也不清除/释放。

复用的情况，我看了一些常见的状态，刚好满足有效期显示又大于一小时都是唯一的。

2024-12-27 15:41 UTC, AtmoOmen commented on UIOptimization/ShowStatusRemainingTime.cs
> +    private static readonly Dictionary<uint, uint> iconStatusPair = new()
> 我也想找别的结构。但不知道 SE 怎么设计的，状态和图标之间没有联系。 ![image](https://private-user-images.githubusercontent.com/99428838/398953795-e7523dda-43f6-4954-955f-f13779908a19.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzUzMTQzMzYsIm5iZiI6MTczNTMxNDAzNiwicGF0aCI6Ii85OTQyODgzOC8zOTg5NTM3OTUtZTc1MjNkZGEtNDNmNi00OTU0LTk1NWYtZjEzNzc5OTA4YTE5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjI3VDE1NDAzNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTYxMTIzOTM5ODk3YmQ1MWVjNTcyYThiNmQ0Zjc0OWNmZmY5ZDUzOWM0YzA1MTQ2OWEwZmQyMDkwZTA5ZGQ3MjAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.f_GEOBGyY___UjROu3j5A3qMLr1CbNTsWY_paveqxLw) 状态过期后只是单纯把 OwnerNode 给不可见，内容也不清除/释放。
> 
> 复用的情况，我看了一些常见的状态，刚好满足有效期显示又大于一小时都是唯一的。

Addon 一般很少存储有用的数据, 基本都是 Agent, StringArray 等等存储

2024-12-30 07:49 UTC, DueDine commented on UIOptimization/ShowStatusRemainingTime.cs
> +    private static readonly Dictionary<uint, uint> iconStatusPair = new()
在 NumberArray 找到了一组奇怪的数字，虽然看不出来规律，但和 Status 刚好一一对应。
![Screenshot 2024-12-30 062956](https://github.com/user-attachments/assets/d727bdf9-5113-4737-9250-c8ee14af6360)

2025-01-06 11:44 UTC, DueDine commented
猫耳娘啥时候有空看一眼 如果不太行的话我就自用啦 @AtmoOmen

2025-01-12 07:14 UTC, KirisameVanilla commented on UIOptimization/ShowStatusRemainingTime.cs
> +                           .ToString(@"hh\hmm\m");
时间格式建议写个ConfigUI让玩家自行设置

2025-01-12 08:59 UTC, DueDine commented on UIOptimization/ShowStatusRemainingTime.cs
> +                           .ToString(@"hh\hmm\m");
图标之间的距离最多4个数字 再多很容易会覆盖别的显示时间

2025-01-12 09:03 UTC, KirisameVanilla commented on UIOptimization/ShowStatusRemainingTime.cs
> +                           .ToString(@"hh\hmm\m");
所以说让玩家自行设置

2025-01-12 09:04 UTC, KirisameVanilla commented on UIOptimization/ShowStatusRemainingTime.cs
> +                           .ToString(@"hh\hmm\m");
包括需要精确显示时间的status种类也可以写设置里面让玩家自己选

2025-01-18 07:16 UTC, AtmoOmen requested changes

2025-01-18 07:16 UTC, AtmoOmen commented on UIOptimization/ShowStatusRemainingTime.cs
> +        if (localPlayer is null || DService.Condition[ConditionFlag.InCombat]) return;
改为 `DService.ClientState.LocalPlayer is not { } localPlayer`

2025-01-18 07:16 UTC, AtmoOmen commented on UIOptimization/ShowStatusRemainingTime.cs
> +            var text = SeString.Parse(stringArray->StringArray[37 + i]).ToString();
请检查 text 是否为空以便尽早 continue

2025-01-18 07:16 UTC, AtmoOmen commented on UIOptimization/ShowStatusRemainingTime.cs
> +       base.Uninit();
无用的 `base.Uninit()` 请删除

2025-01-18 09:22 UTC, merged