添加自动整理物品模块
Dalamud-DailyRoutines/DailyRoutines.ModulesPublic pull request #2
Opened 2024-12-20 15:43 UTC by TheDeathDragon

2024-12-20 15:49 UTC, TheDeathDragon commented
已经参考您 DC 给的修改建议，
- 直接 `ref` 配置类实例里面的字段
- 配置加载判空
- 用 Chat 方式打印
- 界面元素添加了 `GlobalFontScale` 动态调整
- 然后加入了更多区域判断，刚才也在游戏里面日随 PVP 等打了一轮验证OK
- 尽可能地使用静态方法和静态字段

有空的话还请 Review 一下代码

2024-12-21 06:42 UTC, AtmoOmen requested changes

2024-12-21 06:42 UTC, AtmoOmen commented on General/AutoSortItems.cs
> +        var isPveMap = currentMapData.TerritoryType.Row > 0 &&
你下面不是已经有 IsValidPveDuty 方法了吗

2024-12-21 06:42 UTC, AtmoOmen commented on General/AutoSortItems.cs
> +    private bool? CheckCanSort()
建议写成单独的判断方法, 不要由这个方法来触发后续
而是写单独的 Enqueue 方法, 同时 Enqueue 可用性检查、判断，在可用性检查里若不符合条件 Abort 掉

2024-12-21 06:42 UTC, AtmoOmen commented on General/AutoSortItems.cs
> +    private void OnZoneChanged(ushort zone)
建议写成单独的判断方法, 不要由这个方法来触发后续
而是写单独的 Enqueue 方法, 同时 Enqueue 可用性检查、判断，在可用性检查里若不符合条件 Abort 掉

而且你这里和CheckCanSort有判断逻辑重复

2024-12-21 06:42 UTC, AtmoOmen commented on General/AutoSortItems.cs
> +            Chat(new SeStringBuilder().AddUiForeground(GetLoc("AutoSortItems-SortMessage"), 506).Build());
直接 Chat 方法传入 string 类型信息就行, 里面已经包装好了颜色

2024-12-21 06:42 UTC, AtmoOmen commented on General/AutoSortItems.cs
> +        if (ImGui.BeginTable("SortingTable", 3, ImGuiTableFlags.Borders | ImGuiTableFlags.RowBg))
换成 ImRaii.Table, 使用 using 语句

2024-12-21 15:22 UTC, closed without merging