添加模块：固定召唤物位置 Fixed Pet Position
Dalamud-DailyRoutines/DailyRoutines.ModulesPublic pull request #5
Opened 2024-12-22 06:11 UTC by kanyeishere

进入八人副本后，若当前场上存在自身召唤物，则自动将召唤物固定于指定位置

2024-12-22 10:39 UTC, kanyeishere commented
![image](https://github.com/user-attachments/assets/b139a07a-cbf9-4fd3-ad6e-a87cceec7a0d)
![image](https://github.com/user-attachments/assets/48c217dc-cedc-40ba-98be-f9b3aa67b708)

请问一下，我在副本内动态修改这两个坐标点的值之后，会出现这样的情况，召唤物在两点之间来回走动，应该如何解决?


我尝试过  TaskHelper.RemoveAllTasks()，这个方法需要传入一个weight参数，可是我不清楚这个参数应该填什么

2024-12-23 05:21 UTC, AtmoOmen requested changes

2024-12-23 05:21 UTC, AtmoOmen commented on Action/FixedPetPosition.cs
> +                             new Vector2(480f * GlobalFontScale, 0)))
不要写死宽度, 用 `ImGui.GetContentRegionAvail()` 去计算

2024-12-23 05:21 UTC, AtmoOmen commented on Action/FixedPetPosition.cs
> +            ImGui.TableSetupColumn("添加", ImGuiTableColumnFlags.WidthFixed, 25f * GlobalFontScale);
按钮列不要写死宽度, 不同 Style 下处理不同, 不能用 GlobalFontScale 计算
考虑 `ImGui.GetTextLineHeightWithSpacing()` 或 `ImGui.CalcTextSize() +  2 * ImGui.GetStyle().ItemSpacing.X`

2024-12-23 05:21 UTC, AtmoOmen commented on Action/FixedPetPosition.cs
> +            ImGui.TableSetupColumn("区域ID", ImGuiTableColumnFlags.WidthFixed, 80f * GlobalFontScale);
同上, 用 `ImGui.CalcTextSize()`

2024-12-23 05:21 UTC, AtmoOmen commented on Action/FixedPetPosition.cs
> +            ImGui.TableSetupColumn("进入战斗后生效(秒)", ImGuiTableColumnFlags.WidthFixed, 160f * GlobalFontScale);
同上, 用 `ImGui.CalcTextSize()`

2024-12-23 05:21 UTC, AtmoOmen commented on Action/FixedPetPosition.cs
> +            ImGui.TableSetupColumn("Y 坐标", ImGuiTableColumnFlags.WidthFixed, 80f * GlobalFontScale);
同上, 用 `ImGui.CalcTextSize()`

2024-12-23 05:21 UTC, AtmoOmen commented on Action/FixedPetPosition.cs
> +            ImGui.TableSetupColumn("X 坐标", ImGuiTableColumnFlags.WidthFixed, 80f * GlobalFontScale);
同上, 用 `ImGui.CalcTextSize()`

2024-12-23 05:21 UTC, AtmoOmen commented on Action/FixedPetPosition.cs
> +                    if (ImGui.InputInt($"##DutyID_{i}", ref editingDutyId, 0, 0))
Input 的处理要结合 if 和 `ImGui.IsItemDeactivatedAfterEdit()`, 现在的逻辑下随便输入什么都会激活

2024-12-23 05:21 UTC, AtmoOmen commented on Action/FixedPetPosition.cs
> +                    if (ImGui.InputInt($"##Time_{i}", ref timeInSeconds, 0, 0))
同上

2024-12-23 05:21 UTC, AtmoOmen commented on Action/FixedPetPosition.cs
> +                    if (ImGui.InputFloat($"##PosX_{i}", ref posX, 0f, 0f, "%.3f"))
同上

2024-12-23 05:21 UTC, AtmoOmen commented on Action/FixedPetPosition.cs
> +                    if (ImGui.InputFloat($"##PosZ_{i}", ref posZ, 0f, 0f, "%.3f"))
同上

2024-12-23 05:21 UTC, AtmoOmen commented on Action/FixedPetPosition.cs
> +                    if (ImGui.Button($"{GetLoc("FixedPetPosition-Delete")}##Schedule_{i}"))
Delete 已有字符串, 请复用, 不要新增

2024-12-23 05:21 UTC, AtmoOmen commented on Action/FixedPetPosition.cs
> +        if (ImGui.BeginTable("PositionSchedulesTable", 6, ImGuiTableFlags.Borders | ImGuiTableFlags.RowBg | ImGuiTableFlags.Resizable, // 允许拖动列宽
表格请用 `ImRaii.Table` 结合 `using` 语句

2024-12-23 05:21 UTC, AtmoOmen commented on Action/FixedPetPosition.cs
> +                        i--; // 修正索引，避免下标越界
直接 continue 即可, 不需要再操作索引

2024-12-23 05:21 UTC, AtmoOmen commented on Action/FixedPetPosition.cs
> +        public int DutyId { get; set; }        // 副本ID
建议写清楚是 区域 ID

2024-12-23 05:21 UTC, AtmoOmen commented on Action/FixedPetPosition.cs
> +        public List<PositionSchedule> PositionSchedules = new();
建议写成字典, 区域为键, List 为值, 提高查找效率

2024-12-23 05:21 UTC, AtmoOmen commented on Action/FixedPetPosition.cs
> +        var location = new Vector3(posX, petLocation.Y, posZ); // 保持宠物当前高度
使用 `MovementManager.TryDetectGroundDownwards()` 动态获取地面高度

2024-12-23 07:14 UTC, kanyeishere commented on Action/FixedPetPosition.cs
> +                             new Vector2(480f * GlobalFontScale, 0)))
已修改

2024-12-23 07:14 UTC, kanyeishere commented on Action/FixedPetPosition.cs
> +            ImGui.TableSetupColumn("添加", ImGuiTableColumnFlags.WidthFixed, 25f * GlobalFontScale);
已修改

2024-12-23 07:14 UTC, kanyeishere commented on Action/FixedPetPosition.cs
> +            ImGui.TableSetupColumn("区域ID", ImGuiTableColumnFlags.WidthFixed, 80f * GlobalFontScale);
已修改

2024-12-23 07:14 UTC, kanyeishere commented on Action/FixedPetPosition.cs
> +            ImGui.TableSetupColumn("进入战斗后生效(秒)", ImGuiTableColumnFlags.WidthFixed, 160f * GlobalFontScale);
已修改

2024-12-23 07:14 UTC, kanyeishere commented on Action/FixedPetPosition.cs
> +            ImGui.TableSetupColumn("X 坐标", ImGuiTableColumnFlags.WidthFixed, 80f * GlobalFontScale);
已修改

2024-12-23 07:15 UTC, kanyeishere commented on Action/FixedPetPosition.cs
> +                    if (ImGui.InputInt($"##DutyID_{i}", ref editingDutyId, 0, 0))
已修改

2024-12-23 07:15 UTC, kanyeishere commented on Action/FixedPetPosition.cs
> +                    if (ImGui.InputInt($"##Time_{i}", ref timeInSeconds, 0, 0))
已修改

2024-12-23 07:15 UTC, kanyeishere commented on Action/FixedPetPosition.cs
> +                    if (ImGui.InputFloat($"##PosX_{i}", ref posX, 0f, 0f, "%.3f"))
已修改

2024-12-23 07:15 UTC, kanyeishere commented on Action/FixedPetPosition.cs
> +                    if (ImGui.InputFloat($"##PosZ_{i}", ref posZ, 0f, 0f, "%.3f"))
已修改

2024-12-23 07:18 UTC, kanyeishere commented on Action/FixedPetPosition.cs
> +        var location = new Vector3(posX, petLocation.Y, posZ); // 保持宠物当前高度
已修改

2024-12-23 07:18 UTC, kanyeishere commented on Action/FixedPetPosition.cs
> +        if (ImGui.BeginTable("PositionSchedulesTable", 6, ImGuiTableFlags.Borders | ImGuiTableFlags.RowBg | ImGuiTableFlags.Resizable, // 允许拖动列宽
已修改

2024-12-23 07:18 UTC, kanyeishere commented on Action/FixedPetPosition.cs
> +                        i--; // 修正索引，避免下标越界
已修改

2024-12-23 07:18 UTC, kanyeishere commented on Action/FixedPetPosition.cs
> +        public int DutyId { get; set; }        // 副本ID
已修改

2024-12-23 07:18 UTC, kanyeishere commented on Action/FixedPetPosition.cs
> +                    if (ImGui.Button($"{GetLoc("FixedPetPosition-Delete")}##Schedule_{i}"))
已修改

2024-12-23 07:35 UTC, kanyeishere commented on Action/FixedPetPosition.cs
> +        public List<PositionSchedule> PositionSchedules = new();
已修改

2024-12-23 07:35 UTC, kanyeishere commented on Action/FixedPetPosition.cs
> +            ImGui.TableSetupColumn("Y 坐标", ImGuiTableColumnFlags.WidthFixed, 80f * GlobalFontScale);
已修改

2024-12-23 14:12 UTC, AtmoOmen approved these changes

2024-12-23 14:12 UTC, merged