添加模块：占星技能优化
Dalamud-DailyRoutines/DailyRoutines.ModulesPublic pull request #6
Opened 2024-12-23 01:58 UTC by haku-huang

**根据预设的一系列规则重定向发卡和单体治疗技能目标。**

**重定向发卡：**
当技能”出卡I“不选择目标释放时，将默认的目标从自身更改至规则制定的目标。
发卡重定向规则：
常规（根据目前版本的职业输出能力，选择发卡目标。）
高级 （根据小队成员Logs记录的rDPS，分配目标。）

**重定向单体治疗：**
当单体治疗技能不选择目标释放时，将默认的目标从自身更改至规则制定的目标。
重定向规则：
选择队员中血量比最低且低于指定阈值的成员。
阻止过量治疗：
当全队血量均高于阈值时，阻止无目标的单体治疗技能的释放。

2024-12-23 06:35 UTC, AtmoOmen requested changes

2024-12-23 06:35 UTC, AtmoOmen commented on Action/AstHelper.cs
> +using System.Text.Json.Serialization;
请统一使用 `Newtonsoft.Json`

2024-12-23 06:35 UTC, AtmoOmen commented on Action/AstHelper.cs
> +        var region = "CN"; // cn client
请加入国际服处理逻辑

2024-12-23 23:02 UTC, haku-huang commented
已按照 comments 修改。

2024-12-25 16:41 UTC, KirisameVanilla commented on Action/AstHelper.cs
> +        if (ImGui.RadioButton($"{GetLoc("On")} ({GetLoc("ASTHelper-EasyHeal-OnDescription")})", ModuleConfig.EasyHeal == EasyHealStatus.Enable))
看了一下loc，感觉“On”可以使用GetLoc("Enable") ，然后把off改成Disable?
~不知道具体功能，只是看loc看的~

2024-12-25 16:45 UTC, haku-huang commented on Action/AstHelper.cs
> +        if (ImGui.RadioButton($"{GetLoc("On")} ({GetLoc("ASTHelper-EasyHeal-OnDescription")})", ModuleConfig.EasyHeal == EasyHealStatus.Enable))
其实是因为 GetLoc 里还没有 "Disable"，笑。
那我在那边也加一下。

2024-12-25 16:56 UTC, haku-huang commented on Action/AstHelper.cs
> +        if (ImGui.RadioButton($"{GetLoc("On")} ({GetLoc("ASTHelper-EasyHeal-OnDescription")})", ModuleConfig.EasyHeal == EasyHealStatus.Enable))
Updated ♥

2024-12-26 06:33 UTC, merged